 Hint: Loaded cuda/12.1 but please note that no NVIDIA driver is installed on this machine.
/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2023.03/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: Using fork() can cause Polars to deadlock in the child process.
In addition, using fork() with Python in general is a recipe for mysterious
deadlocks and crashes.

The most likely reason you are seeing this error is because you are using the
multiprocessing module on Linux, which uses fork() by default. This will be
fixed in Python 3.14. Until then, you want to use the "spawn" context instead.

See https://docs.pola.rs/user-guide/misc/multiprocessing/ for details.

If you really know what your doing, you can silence this warning with the warning module
or by setting POLARS_ALLOW_FORKING_THREAD=1.

  self.pid = os.fork()
  0%|[32m          [0m| 0/65 [00:00<?, ? file(s)/s]100%|[32mâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[0m| 65/65 [00:20<00:00,  3.20 file(s)/s]100%|[32mâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[0m| 65/65 [00:20<00:00,  3.20 file(s)/s]
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 14826971.0 ON ravc4065 CANCELLED AT 2025-01-09T16:17:49 ***
srun: got SIGCONT
slurmstepd: error: *** JOB 14826971 ON ravc4065 CANCELLED AT 2025-01-09T16:17:49 ***
srun: forcing job termination
